### ISSUE TITLE
Question about training stage 0

### ISSUE THREAD

**Issue by Zehaos** [takiyu/DeepPose#1]
Hi, takiyu
My training got stuck in "start to load one epoch" when I train stage 0.
`
[2016/06/23 15:32:53] INFO (16675) loops : Start to load one epoch (train)
`
I am on GPU mode. Do you have any idea? Thanks~

**Comment by takiyu** [comment]
Thanks to use my program.

I think the training was already started or it took time to load images simply.
In my implementation, loading and training run in parallel, so logging order is sometimes wrong.
Please check your CPU/GPU usage.

Now I removed debug code and enable debug logging, so pull again please.

**Comment by Zehaos** [comment]
Thank you for your reply. I will try it soon : )

**Comment by Zehaos** [comment]
Hi, takiyu,
I have tried the new code, it is sad that the problem still exists(both CPU mode and GPU mode). I checked CPU/GPU usage, It seems the data have been push to GPU memory( 789MB usage), but both CPU and GPU were not working(I wait about 20 mins, the usage is very low).

**Comment by takiyu** [comment]
> the data have been push to GPU memory

This means that training loop had been received the data correctly,
so I think the problem is with core process of training.

On my environment, GPU memory usage is over 2GB with default settings.
If your GPU have the smaller capacity, please set `BATCH_SIZE` to 8 or 4 in `settings.json`.

**Comment by Zehaos** [comment]
Actually I have 4GB GPU memory, so, there is no problem with my hardware capability. 
Could you please tell me the detail of your development environment ( Chainer version etc.)?
Thank you for your patience~

**Comment by takiyu** [comment]
My environments are
- Ubuntu 14.04
- Python 2.7
- Chainer 1.9.1
- OpenCV 2.4.8
- Flask 0.11.1
- Flask_SocketIO 2.4

and
- Arch Linux (Latest)
- Python 3.5
- Chainer 1.9.1
- OpenCV 3.1.0
- Flask 0.10.1
- Flask_SocketIO 2.2

If you do not have any idea, please add some `print()` to scripts and trace them (`train_pose_loop` in `scripts/loops.py` may contain the cause).

**Comment by Zehaos** [comment]
Got it~ Thank you very much.
