### ISSUE TITLE
How resume works?

### ISSUE THREAD

**Issue by MaxChu719** [takiyu/DeepPose#4]
I have pull your code and it is running on my Mac. Since i am using CPU mode, it is quite slow (i think it is using 2 cpus now instead of 4 cpus that i have on my Mac).

If i press control+c now to terminate it, how can i resume it later?

**Comment by takiyu** [comment]
Yes, you can resume the latest state with `--resume` argument.
However CPU mode is too slow, so I recommend you GPU mode to train DNN.

**Comment by MaxChu719** [comment]
Thanks for the reply! My machine is MacBook Pro (13-inch, Mid 2012) and the display card is Intel HD Graphics 4000 1536 MB. Time for me to buy a new one with Nvidia display...
