### ISSUE TITLE
Running on Windows 10

### ISSUE THREAD

**Issue by MaxChu719** [takiyu/DeepPose#5]
I have installed all the dependencies correctly, but i still get the error:

```
C:\Users\User\Documents\PhD_Research\Example\DeepPose>python scripts\train.py
Traceback (most recent call last):
  File "scripts\train.py", line 50, in <module>
    cuda.check_cuda_available()
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\chainer-1.16.0-py3.5-win-amd64.egg\chainer\cuda.py", line 85, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/pfnet/chainer#installation).CuPy is not correctly installed. Please check your environment, uninstall Chainer and reinstall it with `pip install chainer --no-cache-dir -vvvv`.
``
```

**Comment by takiyu** [comment]
It is an error in Chainer.
Please read the following document and reinstall Chainer with CUDA to use GPU.
http://docs.chainer.org/en/stable/install.html

**Comment by MaxChu719** [comment]
I am using GTX 745, i can't find this card in the supported list for CUDA. Does it mean that i cannot use this to accelerate the learning?

**Comment by takiyu** [comment]
http://www.geforce.com/hardware/desktop-gpus/geforce-gtx-745-oem/specifications
According to the specifications GTX 745 have some CUDA cores, so I think you can use CUDA.

Before using Chainer, it is better to try raw CUDA codes to check CUDA installation.
https://developer.nvidia.com/cuda-code-samples

**Comment by MaxChu719** [comment]
What is meaning of the exact value of `gpus` parameter in the `settings.json`?

**Comment by takiyu** [comment]
`"GPU": -1` means CPU, `"GPU": 0` means first GPU, `"GPU": 1` means second GPU and so on.
